# Generated by Django 3.2 on 2021-05-08 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_default', models.BooleanField(default=False, verbose_name='Показывать по умлочанию')),
                ('title', models.CharField(max_length=255, verbose_name='Название города')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Активность')),
                ('image', models.ImageField(blank=True, null=True, upload_to='comments/', verbose_name='Фото пользователя')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('text', models.TextField(verbose_name='Текст комментария')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_on_index', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('image_small', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Маленькое фото товара')),
                ('image_big', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Большое фото товара')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Цена за 1 комплект')),
                ('count', models.PositiveIntegerField(default=0, null=True, verbose_name='Максимальное количество товаров')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(help_text='Формат ссылки: "https://www.youtube.com/watch?v=otCL-UXvcvo"', max_length=255, verbose_name='Ссылка на видео')),
                ('coords', models.CharField(help_text='Формат данных: "55.71, 89.99"', max_length=255, verbose_name='Координаты метки на карте')),
                ('balloon_text', models.TextField(verbose_name='Контент балуна на карте')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='main.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
